//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AudioOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AudioOutputType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}DIABaseType">
 *       &lt;sequence>
 *         &lt;element name="AudioOutputCapability" type="{urn:tva:mpeg21:2012}AudioOutputCapabilityBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioOutputType", propOrder = {
    "audioOutputCapability"
})
public class AudioOutputType
    extends DIABaseType
{

    @XmlElement(name = "AudioOutputCapability")
    protected List<AudioOutputCapabilityBaseType> audioOutputCapability;

    /**
     * Gets the value of the audioOutputCapability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioOutputCapability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioOutputCapability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioOutputCapabilityBaseType }
     * 
     * 
     */
    public List<AudioOutputCapabilityBaseType> getAudioOutputCapability() {
        if (audioOutputCapability == null) {
            audioOutputCapability = new ArrayList<AudioOutputCapabilityBaseType>();
        }
        return this.audioOutputCapability;
    }

}
