//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodecParameterMemoryBandwidthType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodecParameterMemoryBandwidthType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}CodecParameterBaseType">
 *       &lt;sequence>
 *         &lt;element name="MemoryBandwidth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodecParameterMemoryBandwidthType", propOrder = {
    "memoryBandwidth"
})
public class CodecParameterMemoryBandwidthType
    extends CodecParameterBaseType
{

    @XmlElement(name = "MemoryBandwidth")
    protected BigInteger memoryBandwidth;

    /**
     * Gets the value of the memoryBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMemoryBandwidth() {
        return memoryBandwidth;
    }

    /**
     * Sets the value of the memoryBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMemoryBandwidth(BigInteger value) {
        this.memoryBandwidth = value;
    }

}
