//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DIABaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DIABaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{urn:tva:metadata:2012}TVAIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIABaseType")
@XmlSeeAlso({
    DescriptionMetadataType.ClassificationSchemeAlias.class,
    DescriptionMetadataType.class,
    SoundfieldType.class,
    DataIOType.class,
    GenericPenType.class,
    ChromaticityType.class,
    AudioOutputType.class,
    StereoscopicVideoConversionType.class,
    StorageType.class,
    DirectivityType.class,
    NaturalEnvironmentType.class,
    ResolutionType.class,
    GenericMouseType.class,
    GeneralResourcePrioritiesType.class,
    UserType.class,
    DeviceBenchmarkBaseType.class,
    PerceptualParametersType.class,
    SpecificResourceConversionsType.class,
    UpdateIntervalType.class,
    DisplayType.class,
    ResourceConversionType.class,
    TextFocusOfAttentionType.class,
    StorageCharacteristicBaseType.class,
    AudiogramType.class,
    DataIOCharacteristicBaseType.class,
    ColorVisionDeficiencyType.class,
    UserInteractionInputType.class,
    CodecCapabilityBaseType.class,
    BenchmarkType.class,
    CodecParameterBaseType.class,
    TerminalType.class,
    VisualImpairmentDegreeType.class,
    ImpulseResponseType.class,
    AudioOutputCapabilityBaseType.class,
    NetworkCharacteristicBaseType.class,
    DisplayCapabilityBaseType.class,
    GenrePrioritiesType.class,
    UserCharacteristicBaseType.class,
    ConversionType.class,
    LowVisionImpairmentType.class,
    AudioModeType.class,
    NetworkType.class,
    UserInteractionInputSupportBaseType.class,
    ModalityPrioritiesType.class,
    ColorPreferenceType.class,
    FontType.class,
    ErraticityType.class,
    TerminalCapabilityBaseType.class,
    DIADescriptionType.class,
    NaturalEnvironmentCharacteristicBaseType.class,
    SpecificResourcePrioritiesType.class
})
public abstract class DIABaseType {

    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
