//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigitalExportRightType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DigitalExportRightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="DigitalExportRightFlagNotGranted" type="{urn:tva:rmpi:2012}NotGrantedType"/>
 *           &lt;sequence>
 *             &lt;element name="DigitalExportRightFlagGranted" type="{urn:tva:rmpi:2012}GrantedType"/>
 *             &lt;element name="DigitalExportControl" type="{urn:tva:rmpi:2012}DigitalExportControlType" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DigitalExportRightType", namespace = "urn:tva:rmpi:2012", propOrder = {
    "digitalExportRightFlagNotGranted",
    "digitalExportRightFlagGranted",
    "digitalExportControl"
})
public class DigitalExportRightType {

    @XmlElement(name = "DigitalExportRightFlagNotGranted")
    protected NotGrantedType digitalExportRightFlagNotGranted;
    @XmlElement(name = "DigitalExportRightFlagGranted")
    protected GrantedType digitalExportRightFlagGranted;
    @XmlElement(name = "DigitalExportControl")
    protected DigitalExportControlType digitalExportControl;

    /**
     * Gets the value of the digitalExportRightFlagNotGranted property.
     * 
     * @return
     *     possible object is
     *     {@link NotGrantedType }
     *     
     */
    public NotGrantedType getDigitalExportRightFlagNotGranted() {
        return digitalExportRightFlagNotGranted;
    }

    /**
     * Sets the value of the digitalExportRightFlagNotGranted property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotGrantedType }
     *     
     */
    public void setDigitalExportRightFlagNotGranted(NotGrantedType value) {
        this.digitalExportRightFlagNotGranted = value;
    }

    /**
     * Gets the value of the digitalExportRightFlagGranted property.
     * 
     * @return
     *     possible object is
     *     {@link GrantedType }
     *     
     */
    public GrantedType getDigitalExportRightFlagGranted() {
        return digitalExportRightFlagGranted;
    }

    /**
     * Sets the value of the digitalExportRightFlagGranted property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantedType }
     *     
     */
    public void setDigitalExportRightFlagGranted(GrantedType value) {
        this.digitalExportRightFlagGranted = value;
    }

    /**
     * Gets the value of the digitalExportControl property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalExportControlType }
     *     
     */
    public DigitalExportControlType getDigitalExportControl() {
        return digitalExportControl;
    }

    /**
     * Sets the value of the digitalExportControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalExportControlType }
     *     
     */
    public void setDigitalExportControl(DigitalExportControlType value) {
        this.digitalExportControl = value;
    }

}
