//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.04 at 03:25:31 PM COT 
//


package co.com.edutva.edutvav1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EducationalContextAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EducationalContextAttributesType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:metadata:extended:2012}ContextAttributesType">
 *       &lt;sequence>
 *         &lt;element name="EducationalResource" type="{urn:tva:metadata:extended:2012}EducationalResourceType"/>
 *         &lt;element name="EducationalContext" type="{urn:tva:metadata:2012}ControlledTermType" maxOccurs="unbounded"/>
 *         &lt;element name="EducationalAudience" type="{urn:tva:metadata:extended:2012}EducationalAudienceType"/>
 *         &lt;element name="Annotation" type="{urn:tva:mpeg7:2008}TextualType" maxOccurs="unbounded"/>
 *         &lt;element name="EducationalResults" type="{urn:tva:metadata:extended:2012}EducationalResultsType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EducationalContextAttributesType", namespace = "urn:tva:metadata:extended:2012", propOrder = {
    "educationalResource",
    "educationalContext",
    "educationalAudience",
    "annotation",
    "educationalResults"
})
public class EducationalContextAttributesType
    extends ContextAttributesType
{

    @XmlElement(name = "EducationalResource", required = true)
    protected EducationalResourceType educationalResource;
    @XmlElement(name = "EducationalContext", required = true)
    protected List<ControlledTermType> educationalContext;
    @XmlElement(name = "EducationalAudience", required = true)
    protected EducationalAudienceType educationalAudience;
    @XmlElement(name = "Annotation", required = true)
    protected List<TextualType> annotation;
    @XmlElement(name = "EducationalResults", required = true)
    protected EducationalResultsType educationalResults;

    /**
     * Gets the value of the educationalResource property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalResourceType }
     *     
     */
    public EducationalResourceType getEducationalResource() {
        return educationalResource;
    }

    /**
     * Sets the value of the educationalResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalResourceType }
     *     
     */
    public void setEducationalResource(EducationalResourceType value) {
        this.educationalResource = value;
    }

    /**
     * Gets the value of the educationalContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the educationalContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEducationalContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlledTermType }
     * 
     * 
     */
    public List<ControlledTermType> getEducationalContext() {
        if (educationalContext == null) {
            educationalContext = new ArrayList<ControlledTermType>();
        }
        return this.educationalContext;
    }

    /**
     * Gets the value of the educationalAudience property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalAudienceType }
     *     
     */
    public EducationalAudienceType getEducationalAudience() {
        return educationalAudience;
    }

    /**
     * Sets the value of the educationalAudience property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalAudienceType }
     *     
     */
    public void setEducationalAudience(EducationalAudienceType value) {
        this.educationalAudience = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextualType }
     * 
     * 
     */
    public List<TextualType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<TextualType>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the educationalResults property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalResultsType }
     *     
     */
    public EducationalResultsType getEducationalResults() {
        return educationalResults;
    }

    /**
     * Sets the value of the educationalResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalResultsType }
     *     
     */
    public void setEducationalResults(EducationalResultsType value) {
        this.educationalResults = value;
    }

}
